# Generated by Django 4.0.5 on 2022-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=5)),
                ('imdb_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('poster', models.CharField(max_length=500)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_watched', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
