# Generated by Django 4.0.5 on 2022-06-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_actors_movie_awards_movie_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
